[feeds]
feedlist = [
    { link = "https://spectremedia.org/feed/podcast/", image = "https://spectremedia.org/wp-content/themes/spectre-v2/favicon.png" },
    { link = "https://www.politis.fr/flux-rss-apps/", title = "Politis", image = "https://www.politis.fr/favicon-32x32.png" },
    { link = "http://www.contretemps.eu/rss", title = "Contretemps", image = "https://www.contretemps.eu/wp-content/uploads/ctt.ico" },
    { link = "https://linsoumission.fr/feed/"},
    { link = "http://melenchon.fr/feed/", title = "JLM Le blog"},
    { link = "https://lecturesantiimperialistes.org/feed/", title = "Lectures Anti-Impérialistes"},
    { link = "https://afriquexxi.info/?page=backend&lang=fr", image = "https://afriquexxi.info/squelettes-2021/favicon/favicon-32x32.png"},
    { link = "https://www.frustrationmagazine.fr/feed.xml", image = "https://frustrationmagazine.fr/img/favicon_light.png" },
    { link = "https://www.revue-ballast.fr/feed/", image = "https://www.revue-ballast.fr/wp-content/uploads/2016/09/ballast_favicon.ico" },
    { link = "https://orientxxi.info/?page=backend&lang=fr" },
    { link = "https://survie.org/spip.php?page=backend" },
    { link = "https://www.revolutionpermanente.fr/spip.php?page=backend&id_mot=5", image = "https://pbs.twimg.com/profile_images/1584923031687806980/SgoWFAk9_400x400.jpg" },
    { link = "https://orgasolitrans.fr/index.php/feed/", title = "L'OST" },
    { link = "https://api.lemediatv.fr/rss.xml", title = "Le Média" },
    { link = "https://backend.streetpress.com/rss.xml", title = "StreetPress", domain = "streetpress.com", image = "https://www.streetpress.com/favicon.ico" },
    { link = "https://api.blast-info.fr/rss.xml", title = "BLAST" },
    { link = "https://www.courrierinternational.com/feed/rubrique/geopolitique/rss.xml", title = "Courrier International", image = "https://www.courrierinternational.com/bucket/assets/e04cb3bc293a7e5fc5bb7702ca8cca95c7ddd8bc/img/logos/favicon.ico" },
    { link = "https://strass-syndicat.org/feed/", title = "Le STRASS" },
    { link = "https://fourth.international/french.rss", title = "IVe Internationale", image = "https://fourth.international/sites/default/files/favicon.ico" },
    { link = "https://npa-lanticapitaliste.org/rss.xml", title = "NPA", image = "https://npa-lanticapitaliste.org/sites/default/files/favicon_1.ico"},
    { link = "https://lafranceinsoumise.fr/feed/", title = "LFI"},
    { link = "https://leftalliance.eu/feed/", title = "EU LEFT Alliance", image = "https://leftalliance.eu/wp-content/uploads/2025/04/cropped-FAVICON-ELA-1-32x32.png"},
    { link = "https://institutlaboetie.fr/feed/", title = "Institut La Boétie", image = "https://institutlaboetie.fr/wp-content/uploads/2020/03/LOGO-FAVICON-150x150.png" },
    { link = "https://api.arretsurimages.net/api/public/rss/all-content", title = "Arrêt sur Images", image = "https://www.arretsurimages.net/assets/img/favicon/favicon-32x32.png" },
    { link = "https://www.monde-diplomatique.fr/rss/", title = "Le monde diplomatique", image = "https://www.monde-diplomatique.fr/favicon.ico"},
    { link = "https://regards.fr/feed/", title = "Regards", image = "https://regards.fr/wp-content/uploads/2024/10/cropped-cropped-favicon-32x32.png"}
]