services:
  gazette:
    image: ghcr.io/haysberg/gazette:latest
    container_name: "gazette-backend"
    restart: unless-stopped
    volumes:
      - tmp:/app/tmp:z
  server:
    image: joseluisq/static-web-server:2-alpine
    container_name: "gazette-frontend"
    ports:
      - 80:80
    restart: unless-stopped
    environment:
      # Note: those envs are customizable but also optional
      - SERVER_ROOT=/var/public
      - SERVER_CACHE_CONTROL_HEADERS=true
    volumes:
      - tmp:/var/public:z
  
volumes:
  tmp: