# Replaces the original file with the minified version
import gzip
import hashlib
import os
import re

import brotli

from csscompressor import compress
from jsmin import jsmin

with open('static/js/index.js') as js_file:
	minified = jsmin(js_file.read())
	with open('static/js/index.min.js', 'w') as minified_js:
		minified_js.write(minified)

with open('static/js/theme.js') as theme_file:
	minified_theme = jsmin(theme_file.read())
	with open('static/js/theme.min.js', 'w') as minified_theme_js:
		minified_theme_js.write(minified_theme)

with open('src/sw.js') as sw_file:
	sw_content = sw_file.read()
	# Inject a content-based cache name so the SW busts cache when assets change
	content_to_hash = b''
	for asset_path in ['static/css/daisy.min.css', 'static/js/index.min.js', 'static/js/theme.min.js']:
		with open(asset_path, 'rb') as af:
			content_to_hash += af.read()
	cache_hash = hashlib.md5(content_to_hash).hexdigest()[:8]
	# The source keeps a stable CACHE_PLACEHOLDER; every build rewrites the
	# generated copy from scratch, so there is no stale-name problem here.
	sw_content = re.sub(r'CACHE_PLACEHOLDER', f'gazette-{cache_hash}', sw_content)
	minified_sw = jsmin(sw_content)
	with open('static/sw.js', 'w') as sw_out:
		sw_out.write(minified_sw)

with open('static/css/style.css', 'r') as css_file:
	css = css_file.read()

# Per-logo favicon theme rules generated by build_tools/favicon_theme.py. Kept
# in a separate file so it can be regenerated without touching style.css.
favicons_css = 'static/css/favicons.css'
if os.path.exists(favicons_css):
	with open(favicons_css) as favicons_file:
		css += '\n' + favicons_file.read()

compressed_css: str = compress(css)
with open('static/css/style.min.css', 'w') as minified_css_file:
	_ = minified_css_file.write(compressed_css)

# Already-compressed formats gain nothing from a second pass (the brotli copy of
# a woff2 is even a few bytes larger), so skip them and their own siblings. The
# web servers fall back to serving the original file.
ALREADY_COMPRESSED = {'.avif', '.br', '.gz', '.ico', '.jpeg', '.jpg', '.png', '.webp', '.woff2'}

for root, dirs, files in os.walk('static'):
	for file in files:
		file_path = os.path.join(root, file)
		if os.path.splitext(file)[1].lower() in ALREADY_COMPRESSED:
			continue
		with open(file_path, 'rb') as f_in:
			data = f_in.read()
		with open(file_path + '.gz', 'wb') as f_out:
			f_out.write(gzip.compress(data))
		with open(file_path + '.br', 'wb') as f_out:
			f_out.write(brotli.compress(data, quality=11))
