"""Generate per-logo CSS so favicons stay legible in both themes.

Many source favicons are dark marks on transparent backgrounds (Contre Attaque,
Disclose, La Quadrature…) and vanish on the dark theme; a few are light marks
that vanish on the light theme. A single background plate cannot suit both, so
each favicon is measured and gets a targeted filter:

- dark marks become white (monochrome) or are lightened (coloured) in dark mode
- light monochrome marks are darkened in light mode

Output goes to static/css/favicons.css, which compress_all.py folds into
style.min.css. Pillow is only needed here (dev), never at deploy time.
"""

import glob
import os
import sys
from pathlib import Path

from PIL import Image

HEADER = '/* Generated by build_tools/favicon_theme.py — do not edit by hand. */'

# A mark is "dark" if it is very dim overall, or mostly near-black pixels.
DARK_LUM = 0.32
DARK_BLACK_SHARE = 0.55
DARK_BLACK_LUM = 0.5
# Below this saturation a dark mark is treated as monochrome (invert to white).
MONO_SAT = 0.20
# Light monochrome marks get darkened in the light theme.
LIGHT_LUM = 0.85
LIGHT_MONO_SAT = 0.12

INVERT = 'brightness(0) invert(1)'
LIGHTEN = 'brightness(2.2) saturate(1.15)'
DARKEN = 'brightness(0)'


def luminance(r: int, g: int, b: int) -> float:
	return (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255


def saturation(r: int, g: int, b: int) -> float:
	high = max(r, g, b) / 255
	if high == 0:
		return 0.0
	return (high - min(r, g, b) / 255) / high


def analyse(path: str) -> tuple[float, float, float] | None:
	image = Image.open(path).convert('RGBA')
	pixels = list(image.getdata())
	opaque = [p for p in pixels if p[3] > 20]
	if not opaque:
		return None
	lum = sum(luminance(*p[:3]) for p in opaque) / len(opaque)
	black = sum(1 for p in opaque if luminance(*p[:3]) < 0.12) / len(opaque)
	sat = sum(saturation(*p[:3]) for p in opaque) / len(opaque)
	return lum, black, sat


def collect() -> tuple[list[str], list[str], list[str]]:
	invert: list[str] = []
	lighten: list[str] = []
	darken: list[str] = []

	for path in sorted(glob.glob('static/favicons/*.avif')):
		if path.endswith('-large.avif'):
			continue
		domain = Path(path).stem
		stats = analyse(path)
		if stats is None:
			continue
		lum, black, sat = stats

		if lum < DARK_LUM or (black >= DARK_BLACK_SHARE and lum < DARK_BLACK_LUM):
			(lighten if sat >= MONO_SAT else invert).append(domain)
		elif lum > LIGHT_LUM and sat < LIGHT_MONO_SAT:
			darken.append(domain)

	return invert, lighten, darken


def rule(domains: list[str], prefix: str, filt: str) -> str:
	selectors = ',\n'.join(
		f'{prefix} img[src*="/favicons/{domain}"]' for domain in domains
	)
	return f'{selectors} {{\n\tfilter: {filt};\n}}'


def indent(text: str, spaces: int = 4) -> str:
	pad = ' ' * spaces
	return '\n'.join(pad + line if line else line for line in text.splitlines())


def main() -> None:
	invert, lighten, darken = collect()

	parts = [HEADER]

	if invert or lighten:
		parts.append('/* Dark marks: render legible on the dark theme. */')
		explicit = ':root[data-theme="dark"]'
		prefers = ':root:not([data-theme="light"])'
		explicit_rules = []
		media_rules = []
		if invert:
			explicit_rules.append(rule(invert, explicit, INVERT))
			media_rules.append(rule(invert, prefers, INVERT))
		if lighten:
			explicit_rules.append(rule(lighten, explicit, LIGHTEN))
			media_rules.append(rule(lighten, prefers, LIGHTEN))
		parts.extend(explicit_rules)
		parts.append(
			'@media (prefers-color-scheme: dark) {\n'
			+ indent('\n\n'.join(media_rules))
			+ '\n}'
		)

	if darken:
		parts.append('/* Light marks: render legible on the light theme. */')
		parts.append(rule(darken, ':root[data-theme="light"]', DARKEN))
		parts.append(
			'@media (prefers-color-scheme: light) {\n'
			+ indent(rule(darken, ':root:not([data-theme])', DARKEN))
			+ '\n}'
		)

	output = 'static/css/favicons.css'
	os.makedirs('static/css', exist_ok=True)
	with open(output, 'w') as f:
		f.write('\n\n'.join(p for p in parts if p) + '\n')

	print(
		f'Wrote {output}: {len(invert)} inverted, {len(lighten)} lightened, '
		f'{len(darken)} darkened.'
	)


if __name__ == '__main__':
	# Allow running from the repo root only.
	if not os.path.isdir('static/favicons'):
		print('run from the repository root', file=sys.stderr)
		sys.exit(1)
	main()
